try {
    myfunction();
} catch (err) {
    console.log(err.message)
}